// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfxvbuxrktitanetjseo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmeHZidXhya3RpdGFuZXRqc2VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NTgwMzUsImV4cCI6MjA1ODAzNDAzNX0.zIWnByUR29W3SLJUV9juIwT3wgdZ_SRbKQh6mF1zp6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);