
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfxvbuxrktitanetjseo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmeHZidXhya3RpdGFuZXRqc2VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NTgwMzUsImV4cCI6MjA1ODAzNDAzNX0.zIWnByUR29W3SLJUV9juIwT3wgdZ_SRbKQh6mF1zp6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Define custom types for our database tables
export type Subject = {
  id: string;
  user_id: string;
  name: string;
  priority: 'high' | 'medium' | 'low';
  color: string;
  total_hours: number;
  completed_hours: number;
  created_at: string;
  updated_at: string;
}

export type StudySession = {
  id: string;
  user_id: string;
  subject_id: string;
  start_time: string;
  end_time: string;
  focus_score?: number;
  created_at: string;
}

export type UserPreference = {
  user_id: string;
  daily_goal_hours: number;
  productive_times: Record<string, number>;
  pomodoro_settings: {
    focusTime: number;
    shortBreakTime: number;
    longBreakTime: number;
    longBreakInterval: number;
  };
  created_at: string;
  updated_at: string;
}

export type Notification = {
  id: string;
  user_id: string;
  title: string;
  message: string;
  type: 'reminder' | 'achievement' | 'update';
  is_read: boolean;
  created_at: string;
}
